import * as path from "path";

export class CodeFile {
  constructor(workdir, dayOfMonth) {
    this.fileName = path.join(workdir, this.createFileName(dayOfMonth));
  }

  createFileName(dayOfMonth) {
    return `day${dayOfMonth}.js`;
  }

  createFileContents() {
    return `// generated by prepare script
export const part1 = (arr) => {
  return false;
};

export const part2 = (arr) => {
  return false;
};\n`;
  }
}
