import { File } from './file.js';

export class CodeFile extends File {
  fileName = `day${this.day}.js`;

  createFileContents () {
    return `// generated by prepare script
export const part1 = (input) => {
  console.log(input);
  return false;
};

export const part2 = (input) => {
  return false;
};\n`;
  }
}
