// generated by prepare script
import { readInput } from "../../helpers/readInput.js";
import { part1, part2 } from "./day12.js";

const parseOpts = { delimiter: '-' };

describe("2021 - Day 12", () => {
  describe("Part 1", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day12/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(exampleInput)).toEqual(10);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day12/input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(input)).toEqual(3713);
      });
    });
  });

  describe("Part 2", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day12/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(exampleInput)).toEqual(36);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day12/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input)).toEqual(91292);
      });
    });
  });
});
