// generated by prepare script
import { part1, part2 } from './day23.js';

describe('2021 - Day 23', () => {
  describe('Part 1', () => {
    const exampleInput = [
      { t: 'B', x: 2, y: 1 },
      { t: 'C', x: 4, y: 1 },
      { t: 'B', x: 6, y: 1 },
      { t: 'D', x: 8, y: 1 },

      { t: 'A', x: 2, y: 2 },
      { t: 'D', x: 4, y: 2 },
      { t: 'C', x: 6, y: 2 },
      { t: 'A', x: 8, y: 2 }
    ];

    const input = [
      { t: 'D', x: 2, y: 1 },
      { t: 'D', x: 4, y: 1 },
      { t: 'A', x: 6, y: 1 },
      { t: 'A', x: 8, y: 1 },

      { t: 'C', x: 2, y: 2 },
      { t: 'C', x: 4, y: 2 },
      { t: 'B', x: 6, y: 2 },
      { t: 'B', x: 8, y: 2 }
    ];

    describe('Example Input', () => {
      it('returns the expected result', () => {
        expect(part1(exampleInput)).toEqual(12521);
      });
    });

    describe.skip('Final Input', () => {
      it('returns the expected result', () => {
        expect(part1(input)).toEqual(16489);
      });
    });
  });

  describe.skip('Part 2', () => {
    const exampleInput = [
      { t: 'B', x: 2, y: 1 },
      { t: 'C', x: 4, y: 1 },
      { t: 'B', x: 6, y: 1 },
      { t: 'D', x: 8, y: 1 },

      { t: 'D', x: 2, y: 2 },
      { t: 'C', x: 4, y: 2 },
      { t: 'B', x: 6, y: 2 },
      { t: 'A', x: 8, y: 2 },

      { t: 'D', x: 2, y: 3 },
      { t: 'B', x: 4, y: 3 },
      { t: 'A', x: 6, y: 3 },
      { t: 'C', x: 8, y: 3 },

      { t: 'A', x: 2, y: 4 },
      { t: 'D', x: 4, y: 4 },
      { t: 'C', x: 6, y: 4 },
      { t: 'A', x: 8, y: 4 }
    ];

    const input = [
      { t: 'D', x: 2, y: 1 },
      { t: 'D', x: 4, y: 1 },
      { t: 'A', x: 6, y: 1 },
      { t: 'A', x: 8, y: 1 },

      { t: 'D', x: 2, y: 2 },
      { t: 'C', x: 4, y: 2 },
      { t: 'B', x: 6, y: 2 },
      { t: 'A', x: 8, y: 2 },

      { t: 'D', x: 2, y: 3 },
      { t: 'B', x: 4, y: 3 },
      { t: 'A', x: 6, y: 3 },
      { t: 'C', x: 8, y: 3 },

      { t: 'C', x: 2, y: 4 },
      { t: 'C', x: 4, y: 4 },
      { t: 'B', x: 6, y: 4 },
      { t: 'B', x: 8, y: 4 }
    ];

    describe.skip('Example Input', () => {
      it('returns the expected result', () => {
        expect(part1(exampleInput)).toEqual(44169);
      });
    });

    describe.skip('Final Input', () => {
      it('returns the expected result', () => {
        expect(part1(input)).toEqual(43413);
      });
    });
  });
});
