// generated by prepare script
import { readInput } from "../../helpers/readInput.js";
import { part1, part2 } from "./day17.js";

const parseOpts = {
  transform: (o) => {
    let [, x1, x2, y1, y2] = o.match(
      /x=(-?\d+)\.+(-?\d+), y=(-?\d+)\.+(-?\d+)$/
    );

    return [
      parseInt(x1, 10),
      parseInt(x2, 10),
      parseInt(y1, 10),
      parseInt(y2, 10),
    ];
  },
};

describe("2021 - Day 17", () => {
  describe("Part 1", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day17/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(exampleInput)).toEqual(45);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day17/input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(input)).toEqual(12090);
      });
    });
  });

  describe("Part 2", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day17/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(exampleInput)).toEqual(112);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day17/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input)).toEqual(true);
      });
    });
  });
});
