// generated by prepare script
export const part1 = (input) => {
  let [probe0, probe1, ...remaining] = input;

  console.log(probe0);
  return false;
};

export const part2 = (input) => {
  return false;
};
