// generated by prepare script
import { readInput } from "../../helpers/readInput.js";
import { part2 } from "./day14.js";

const parseOpts = {
  transform: (o) => {
    const [poly, rulesString] = o.split(/\n{2}/);

    const rules = {};
    rulesString.split(/\n/).forEach((r) => {
      const [match, add] = r.split(" -> ");
      rules[match] = add;
    });

    return [poly, rules];
  },
};

describe("2021 - Day 14", () => {
  describe("Part 1", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day14/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(exampleInput)).toEqual(1588);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day14/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input)).toEqual(3406);
      });
    });
  });

  describe("Part 2", () => {
    describe("10 steps", () => {
      const exampleInput = readInput("./2021/day14/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(exampleInput, 40)).toEqual(2188189693529);
      });
    });

    describe("40 steps", () => {
      const input = readInput("./2021/day14/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input, 40)).toEqual(3941782230241);
      });
    });
  });
});
