// generated by prepare script
import { readInput } from "../../helpers/readInput.js";
import { part1, part2 } from "./day24.js";

const parseOpts = { transform: o => o.split('\n').map(l => l.split(' ')) };

describe.skip("2021 - Day 24", () => {
  describe("Part 1", () => {
    describe.skip("Example Input", () => {
      const exampleInput = readInput("./2021/day24/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(exampleInput)).toEqual(true);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day24/input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(input)).toEqual(true);
      });
    });
  });

  describe("Part 2", () => {
    describe.skip("Example Input", () => {
      const exampleInput = readInput("./2021/day24/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(exampleInput)).toEqual(true);
      });
    });

    describe.skip("Final Input", () => {
      const input = readInput("./2021/day24/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input)).toEqual(true);
      });
    });
  });
});
