// generated by prepare script
export const part1 = ([gx1, gx2, gy1, gy2]) => {
  const checkIfGoal = (x, y) => {
    if (x < gx1 || x > gx2) return false;
    if (y < gy1 || y > gy2) return false;
    return true;
  };

  let maxY = 0;

  const determineIfWillBeGoal = (startVX, startVY) => {
    let [x, y, vX, vY] = [0, 0, startVX, startVY];

    let _maxY = 0;

    while (true) {
      if (y < gy1) return false;
      if (x > gx2) return false;

      const isInGoal = checkIfGoal(x, y);
      if (isInGoal) {
        if (_maxY > maxY) maxY = _maxY;
        return true;
      } else {
        if (y > _maxY) _maxY = y;
      }

      x += vX;
      y += vY;

      vY -= 1;
      if (vX > 0) vX -= 1;
      if (vX < 0) vX += 1;
    }
  };

  for (let vX = 1; vX < gx1; vX += 1) {
    for (let vY = 1; vY < Math.abs(gy1); vY += 1) {
      determineIfWillBeGoal(vX, vY);
    }
  }

  return maxY;
};

export const part2 = ([gx1, gx2, gy1, gy2]) => {
  const checkIfGoal = (x, y) => {
    if (x < gx1 || x > gx2) return false;
    if (y < gy1 || y > gy2) return false;
    return true;
  };

  const determineIfWillBeGoal = (startVX, startVY) => {
    let [x, y, vX, vY] = [0, 0, startVX, startVY];

    while (true) {
      if (y < gy1) return false;
      if (x > gx2) return false;

      const isInGoal = checkIfGoal(x, y);
      if (isInGoal) return true;

      x += vX;
      y += vY;

      vY -= 1;
      if (vX > 0) vX -= 1;
      if (vX < 0) vX += 1;
    }
  };

  let t = 0;

  for (let vX = 0; vX < gx2 * 2; vX += 1) {
    for (let vY = gy1; vY < Math.abs(gy1); vY += 1) {
      t += Number(determineIfWillBeGoal(vX, vY));
    }
  }

  return t;
};
