// generated by prepare script
import { part1, part2 } from './day21.js';

describe('2021 - Day 21', () => {
  describe('Part 1', () => {
    describe('Example Input', () => {
      it('returns the expected result', () => {
        expect(part1([4, 8])).toEqual(739785);
      });
    });

    describe('Final Input', () => {
      it('returns the expected result', () => {
        expect(part1([2, 7])).toEqual(805932);
      });
    });
  });

  describe('Part 2', () => {
    describe('Example Input', () => {
      it('returns the expected result', () => {
        expect(part2([4, 8])).toEqual(444356092776315);
      });
    });

    describe('Final Input', () => {
      it('returns the expected result', () => {
        expect(part2([2, 7])).toEqual(133029050096658);
      });
    });
  });
});
