// generated by prepare script
import { readInput } from "../../helpers/readInput.js";
import { part1, part2 } from "./day13.js";

const parseOpts = { transform: (o) => o.split(/\n{2}/) };

describe("2021 - Day 13", () => {
  describe("Part 1", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day13/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(exampleInput)).toEqual(17);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day13/input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(input)).toEqual(687);
      });
    });
  });

  describe("Part 2", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day13/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(exampleInput)).toEqual(
          [
            `# # # # #`,
            `#       #`,
            `#       #`,
            `#       #`,
            `# # # # #`,
          ].join("\n")
        );
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day13/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input)).toEqual(
          [
            `# # # #     # #     #     #     # #     #     #   # # #     # # # #     # #  `,
            `#         #     #   #   #     #     #   #   #     #     #         #   #     #`,
            `# # #     #         # #       #         # #       # # #         #     #      `,
            `#         #   # #   #   #     #         #   #     #     #     #       #   # #`,
            `#         #     #   #   #     #     #   #   #     #     #   #         #     #`,
            `#           # # #   #     #     # #     #     #   # # #     # # # #     # # #`,
          ].join("\n")
        );
      });
    });
  });
});
