// generated by prepare script
import { readInput } from '../../helpers/readInput.js';
import { part1, part2 } from './day25.js';

const parseOpts = { transform: (o) => o.split(/\n/).map((l) => l.split('')) };

describe('2021 - Day 25', () => {
  describe('Part 1', () => {
    describe('Example Input', () => {
      const exampleInput = readInput('./2021/day25/example-input', parseOpts);

      it('returns the expected result', () => {
        expect(part1(exampleInput)).toEqual(58);
      });
    });

    describe('Final Input', () => {
      const input = readInput('./2021/day25/input', parseOpts);

      it('returns the expected result', () => {
        expect(part1(input)).toEqual(329);
      });
    });
  });

  describe('Part 2', () => {
    describe.skip('Example Input', () => {
      const exampleInput = readInput('./2021/day25/example-input', parseOpts);

      it('returns the expected result', () => {
        expect(part2(exampleInput)).toEqual(true);
      });
    });

    describe.skip('Final Input', () => {
      const input = readInput('./2021/day25/input', parseOpts);

      it('returns the expected result', () => {
        expect(part2(input)).toEqual(true);
      });
    });
  });
});
