// generated by prepare script
import { readInput } from '../../helpers/readInput.js';
import { Engine } from './day24.js';

const parseOpts = { transform: (o) => o.split('\n').map((l) => l.split(' ')) };

describe('2021 - Day 24', () => {
  describe('Part 1', () => {
    describe('Final Input', () => {
      const input = readInput('./2021/day24/input', parseOpts);

      it('returns the expected result', () => {
        const engine = new Engine(input);
        const output = engine.run(6, 5, 9, 8, 4, 9, 1, 9, 9, 9, 7, 9, 3, 9);
        expect(output.z).toEqual(0);
      });
    });
  });

  describe('Part 2', () => {
    describe('Final Input', () => {
      const input = readInput('./2021/day24/input', parseOpts);

      it('returns the expected result', () => {
        const engine = new Engine(input);
        const output = engine.run(1, 1, 2, 1, 1, 6, 1, 9, 5, 4, 1, 7, 1, 3);
        expect(output.z).toEqual(0);
      });
    });
  });
});
