// generated by prepare script
import { readInput } from "../../helpers/readInput.js";
import { part1, part2 } from "./day8.js";

const parseOpts = {
  delimiter: " | ",
  transform: (o) =>
    o.map((r) =>
      r.map((p) => p.split(" ").map((s) => s.split("").sort().join("")))
    ),
};

describe("2021 - Day 8", () => {
  describe("Part 1", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day8/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(exampleInput)).toEqual(26);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day8/input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(input)).toEqual(476);
      });
    });
  });

  describe("Part 2", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day8/example-input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(exampleInput)).toEqual(61229);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day8/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input)).toEqual(1011823);
      });
    });
  });
});
