// generated by prepare script
export const part1 = (arr) => {
  const avg = arr.reduce((p, c, i) => p + (c - p) / (i + 1), 0);
  const min = Math.floor(avg / 2);
  const max = Math.ceil(avg * 2);

  let winner;

  for (let a = min; a <= max; a += 1) {
    let t = arr.reduce((t, b) => t + Math.abs(b - a), 0);
    if (!winner || t < winner) winner = t;
  }

  return winner;
};

export const part2 = (arr) => {
  const avg = arr.reduce((p, c, i) => p + (c - p) / (i + 1), 0);
  const min = Math.floor(avg / 2);
  const max = Math.ceil(avg * 2);

  let winner;

  for (let a = min; a <= max; a += 1) {
    let t = arr.reduce((_t, b) => {
      let t = _t;
      let diff = Math.abs(b - a);
      let gas = 1;

      for (let i = 0; i < diff; i += 1) t += gas++;

      return t;
    }, 0);

    if (!winner || t < winner) winner = t;
  }

  return winner;
};
