// generated by prepare script
import { readInput } from "../../helpers/readInput.js";
import { part1, part2 } from "./day7.js";

const parseOpts = { transform: (o) => o.split(",").map(Number) };

describe("2021 - Day 7", () => {
  describe("Part 1", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day7/example-input", parseOpts);

      it("returns the expected result for example", () => {
        expect(part1(exampleInput)).toEqual(37);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day7/input", parseOpts);

      it("returns the expected result", () => {
        expect(part1(input)).toEqual(340056);
      });
    });
  });

  describe("Part 2", () => {
    describe("Example Input", () => {
      const exampleInput = readInput("./2021/day7/example-input", parseOpts);

      it("returns the expected result for example", () => {
        expect(part2(exampleInput)).toEqual(168);
      });
    });

    describe("Final Input", () => {
      const input = readInput("./2021/day7/input", parseOpts);

      it("returns the expected result", () => {
        expect(part2(input)).toEqual(96592275);
      });
    });
  });
});
