// generated by prepare script
export const part1 = (arr) => {
  const avg = arr.reduce((p, c, i) => p + (c - p) / (i + 1), 0);
  const min = Math.floor(avg / 2);
  const max = Math.ceil(avg * 2);

  const possibles = [];

  for (let a = min; a <= max; a += 1) {
    let t = 0;

    arr.forEach((b) => {
      t += a > b ? a - b : b - a;
    });

    possibles.push(t);
  }

  return Math.min(...possibles);
};

export const part2 = (arr) => {
  const avg = arr.reduce((p, c, i) => p + (c - p) / (i + 1), 0);
  const min = Math.floor(avg / 2);
  const max = Math.ceil(avg * 2);

  const possibles = [];

  for (let a = min; a <= max; a += 1) {
    let t = 0;

    arr.forEach((b) => {
      let minPos = a > b ? b : a;
      let maxPos = a > b ? a : b;
      let gas = 1;
      for (let i = minPos; i < maxPos; i += 1) {
        t += gas;
        gas += 1;
      }
    });

    possibles.push(t);
  }

  return Math.min(...possibles);
};
