// generated by prepare script
import _ from "lodash";

const addPosForPlayer = (p1, p2, c, r) => {
  const s = [p1, p2];
  s[c] = ((s[c] + r - 1) % 10) + 1;
  return s;
};

const rollPart1 = (p1, p2, s1 = 0, s2 = 0, c = 0, r = 0, v = 0) => {
  let [, , _s1, _s2, _c, _r] = [p1, p2, s1, s2, c, r];

  if (r === 3) {
    _r = 1;
    _c = 1 - c;
    if (!c) _s1 += p1;
    else _s2 += p2;
  } else {
    _r += 1;
  }

  if (_s1 >= 1000) return _s2 * v;
  if (_s2 >= 1000) return _s1 * v;

  const _v = v + 1;

  return rollPart1(...addPosForPlayer(p1, p2, _c, _v), _s1, _s2, _c, _r, _v);
};

export const part1 = ([p1, p2]) => rollPart1(p1, p2);

const rollPart2 = _.memoize(
  (p1, p2, s1, s2, c, r) => {
    let [, , _s1, _s2, _c, _r] = [p1, p2, s1, s2, c, r];

    if (r === 3) {
      _r = 1;
      _c = 1 - c;
      if (!c) _s1 += p1;
      else _s2 += p2;
    } else {
      _r += 1;
    }

    if (_s1 >= 21) return [1, 0];
    if (_s2 >= 21) return [0, 1];

    const winners = [0, 0];

    [
      rollPart2(...addPosForPlayer(p1, p2, _c, 1), _s1, _s2, _c, _r),
      rollPart2(...addPosForPlayer(p1, p2, _c, 2), _s1, _s2, _c, _r),
      rollPart2(...addPosForPlayer(p1, p2, _c, 3), _s1, _s2, _c, _r),
    ].forEach((n) => {
      winners[0] += n[0];
      winners[1] += n[1];
    });

    return winners;
  },
  (...args) => args.join(",")
);

export const part2 = ([p1, p2]) => {
  const winnings = rollPart2(p1, p2, 0, 0, 0, 0);
  return Math.max(...winnings);
};
