// generated by prepare script
import { readInput } from '../../helpers/readInput.js';
import { part1, part2 } from './day11.js';

const parseOpts = {
  transform: (o) => o.split(/\r?\n/).map((l) => l.split('').map(Number))
};

describe('2021 - Day 11', () => {
  describe('Part 1', () => {
    describe('Example Input', () => {
      const exampleInput = readInput('./2021/day11/example-input', parseOpts);

      it('returns the expected result', () => {
        expect(part1(exampleInput)).toEqual(1656);
      });
    });

    describe('Final Input', () => {
      const input = readInput('./2021/day11/input', parseOpts);

      it('returns the expected result', () => {
        expect(part1(input)).toEqual(1773);
      });
    });
  });

  describe('Part 2', () => {
    describe('Example Input', () => {
      const exampleInput = readInput('./2021/day11/example-input', parseOpts);

      it('returns the expected result', () => {
        expect(part2(exampleInput)).toEqual(195);
      });
    });

    describe('Final Input', () => {
      const input = readInput('./2021/day11/input', parseOpts);

      it('returns the expected result', () => {
        expect(part2(input)).toEqual(494);
      });
    });
  });
});
